Autodaktarai/Autodaktarai/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('autoservice/', include('autoservice.urls')),
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='autoservice/')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('tinymce/', include('tinymce.urls')),
] + (static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) +
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

Autodaktarai/autoservice/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('owners/', views.owners, name='owners'),
    path('owners/<int:owner_id>', views.owner, name='owner'),
    path('cars/', views.CarListView.as_view(), name='cars'),
    path('cars/<int:pk>', views.CarDetailView.as_view(), name='car-detail'),
    path('search/', views.search, name='search'),
    path('mycars/', views.OwnedCarsByUserListView.as_view(), name='my-owned'),
    path('register/', views.register, name='register'),
    path('profilis/', views.profilis, name='profilis'),
]

Autodaktarai/autoservice/models.py
from django.db import models
import uuid
from django.contrib.auth.models import User
from datetime import date
import pytz
utc=pytz.UTC
from tinymce.models import HTMLField
from PIL import Image

# Create your models here.

class Mechanic(models.Model):
    name = models.CharField('Autoserviso darbuotojas', max_length=100, help_text='Įveskite serviso darbuotojo vardą ir pavardę')

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = 'Mechanikas'
        verbose_name_plural = "Mechanikai"


Types = (
    ('diesel', 'Diesel'),
    ('petrol', 'Petrol'),
    ('gas', 'Gas'),
    ('electric', 'Electric'),
    )

class CarInfo(models.Model):
    car = models.CharField('Automobilio markė ir modelis', max_length=100)
    car_owner = models.ForeignKey('Owner', on_delete=models.SET_NULL, null=True, blank=True, related_name='cars')
    fuel_type = models.CharField(max_length=8, choices=Types, default='Petrol')
    engine = models.CharField(max_length=4, help_text='Automobilio darbinis turis cm3') 
    manufacture_year = models.DateField(auto_now=False, auto_now_add=False)
    plate = models.CharField('Automobilio numeriai', max_length=10)
    vin = models.CharField('Automobilio VIN kodas', max_length=17)
    summary = models.TextField('Automobilio gedimo aprasymas', max_length=1000, help_text='Trumpas gedimu aprasymas')
    mechanic = models.ForeignKey('Mechanic', on_delete=models.SET_NULL, null=True, help_text='Serviso darbuotojas atliekantis darbus')
    car_image = models.ImageField('Car image', upload_to='cars', null=True, blank=True)

    def __str__(self):
        return f'{self.car} {self.plate}, Atsakingas darbuotojas: {self.mechanic}.'
    
class Owner(models.Model):
    name = models.CharField('Automobilio savininko vardas', max_length=20)
    surname = models.CharField('Automobilio savininko pavarde', max_length=20)
    car = models.ForeignKey('CarInfo', on_delete=models.SET_NULL, null=True, blank=True,)
    description = HTMLField()

    def __str__(self):
        return f'{self.name} {self.surname}'
    
    def display_cars(self):
        sarasas = [self.car.car for car in self.cars.all()]
        return ','.join(sarasas)

class CarStatus(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unikalus ID kiekvienam automobiliui')
    car = models.ForeignKey('CarInfo', on_delete=models.SET_NULL, null=True)
    due_finish = models.DateField('Automobilis planuojamas suremontuoti', null=True, blank=True)
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    CAR_STATUS = (
        ('w', 'Laukia darbų pradžios'),
        ('i', 'Vyksta automobilio inspektavimas'),
        ('r', 'Remontuojamas automobilis'),
        ('f', 'Automobilis suremontuotas')
    )

    status = models.CharField(
        max_length=1,
        choices=CAR_STATUS,
        blank=True,
        default='w',
        help_text='Statusas',
    )
    class Meta:
        ordering = ['due_finish']

    def __str__(self):
        return f'{self.id} ({self.car})'
    @property
    def is_overdue(self):
        if self.due_finish and date.today().replace(tzinfo=utc) > self.due_finish.replace(tzinfo=utc):
            return True
        return False
    
class CarReview(models.Model):
    car = models.ForeignKey('Carinfo', on_delete=models.SET_NULL, null=True, blank=True)
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True)
    comment = models.TextField("Gedimas", max_length=150)

    class Meta:
        verbose_name = 'Gedimas'
        verbose_name_plural = 'Gedimai'
        ordering = ['-date_created']

class Profilis(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nuotrauka = models.ImageField(default='img/no-image.png', upload_to='profile_pics')

    def __str__(self):
        return f'{self.user.username} profilis'
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        img = Image.open(self.nuotrauka.path)
        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.nuotrauka.path)

Autodaktarai/autoservice/forms.py
from .models import CarReview, Profilis
from django import forms
from django.contrib.auth.models import User

class CarReviewForm(forms.ModelForm):
    class Meta:
        model = CarReview
        fields = ('comment', 'car', 'owner',)
        widgets = {'car': forms.HiddenInput(), 'owner': forms.HiddenInput()}

class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']


class ProfilisUpdateForm(forms.ModelForm):
    class Meta:
        model = Profilis
        fields = ['nuotrauka']

Autodaktarai/autoservice/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.http import HttpResponse
from .models import Mechanic, Owner, CarInfo, CarStatus
from django.views import generic
from django.core.paginator import Paginator
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import User
from django.views.decorators.csrf import csrf_protect
from django.contrib import messages
from .forms import CarReviewForm, UserUpdateForm, ProfilisUpdateForm
from django.views.generic.edit import FormMixin
from django.contrib.auth.decorators import login_required

# Create your views here.

@csrf_protect
def register(request):
    if request.method == 'POST':
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        password2 = request.POST['password2']
        if password == password2:
            if User.objects.filter(username=username).exists():
                messages.error(request, f'Vartotojo vardas {username} užimtas!')
                return redirect('register')
            else:
                if User.objects.filter(email=email).exists():
                    messages.error(request, f'Vartotojas su el. pa6tu {email} jau užregistruotas')
                    return redirect('register')
                else:
                    User.objects.create_user(username=username, email=email, password=password)
                    messages.info(request, f'Vartotojas {username} sėkmingai užregistruotas')
                    return redirect('login')
        else:
            messages.error(request, 'Slaptažodžiai nesutampa!')
            return redirect('register')
    return render(request, 'register.html')

def index(request):
    car_count = CarStatus.objects.all().count()

    waiting_service = CarStatus.objects.filter(status='w').count()
    
    inspection_service = CarStatus.objects.filter(status='i').count()
    
    repair_service = CarStatus.objects.filter(status='r').count()

    finish_service = CarStatus.objects.filter(status='f').count()

    num_visits = request.session.get('num_visits', 1)
    request.session['num_visits'] = num_visits + 1

    context = {
        'car_count' : car_count,
        'waiting_service' : waiting_service,
        'inspection_service' : inspection_service,
        'repair_service' : repair_service,
        'finish_service' : finish_service,
        'num_visits' : num_visits,
    }

    return render(request, 'index.html', context=context)

def search(request):
    query = request.GET.get('query')
    search_results = CarInfo.objects.filter(Q(car__icontains=query) | Q(plate__icontains=query))
    return render(request, 'search.html', {'cars' : search_results, 'query' : query})

def owners(request):

    paginator = Paginator(Owner.objects.all(), 2)
    page_number = request.GET.get('page')
    paged_owners = paginator.get_page(page_number)
    context = {
        'owners' : paged_owners
    }
    return render(request, 'owners.html', context=context)

def owner(request, owner_id):
    owner = get_object_or_404(Owner, pk=owner_id)
    context = {
        'owner' : owner
    }
    return render(request, 'owner.html', context=context)

class CarListView(generic.ListView):
    model = CarInfo, CarStatus
    template_name = 'car_list.html'
    context_object_name = 'car_list'
    queryset = CarInfo.objects.all()
    paginate_by = 2

    def get_context_data(self, **kwargs):
        context = super(CarListView, self).get_context_data(**kwargs)
        context['data'] = 'random text'
        return context
    
class CarDetailView(FormMixin, generic.DetailView):
    model = CarInfo
    template_name = 'car_detail.html'
    form_class = CarReviewForm

    def get_success_url(self):
        return reverse('car-detail', kwargs={'pk': self.object.id})
    
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)
    
    def form_valid(self, form):
        form.instance.car = self.object
        form.instance.owner = self.request.user
        form.save()
        return super(CarDetailView, self).form_valid(form)


class OwnedCarsByUserListView(LoginRequiredMixin, generic.ListView):
    model = CarStatus
    template_name = 'user_cars.html'
    paginate_by = 10


    def get_queryset(self):
        return CarStatus.objects.filter(owner=self.request.user).order_by('due_finish')

@login_required
def profilis(request):
    if request.method == "POST":
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfilisUpdateForm(request.POST, request.FILES, instance=request.user.profilis)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f"Profilis atnaujintas")
            return redirect('profilis')
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfilisUpdateForm(instance=request.user.profilis)

    context = {
        'u_form': u_form,
        'p_form': p_form,
    }
    return render(request, 'profilis.html', context=context)

Autodaktarai/autoservice/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Autoservisas "Auto daktarai"</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <!-- Add additional CSS in static file -->
        {% load static %}
        <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-2">
                <ul class="sidebar-nav">
                <li><a href="{% url 'index' %}">Home</a></li>
            {% if user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'profilis' %}">
                        <svg class='bi bi-person' width="'1.5em" height="1.5em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" d='M13 14s1 0 1-1-1-4-6-4-6 3-6 4 1 1 1 1h10zm-9.995-.944v-.002.002zM3.022 13h9.956a.274.274 0 00.014-.002l.008-.002c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664a1.05 1.05 0 00.022.004zm9.974.056v-.002.002zM8 7a2 2 0 100-4 2 2 0 000 4zm3-2a3 3 0 11-6 0 3 3 0 016 0z' clip-rule="evenodd"/>
                        </svg>
                Esate prisijungęs, kaip: {{ user.get_username }}</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'my-owned' %}">Mano automobiliai</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}?next=/autoservice">Atsijungti</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'owners' %}">Owners</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'cars' %}">Cars</a></li>
                <li class="nav-item">
                    <form action="{% url 'search' %}" method="get" class="form-inline my-2 my-md-0">
                        <input name="query" class="form-control" type="text" placeholder="Search">
                    </form>
                </li>
            {% else %}
                <li class="nav-item"><a class="nav-link" href="{% url 'login' %}?next={{request.path}}">Prisijungti</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'register'%}">Registruotis</a></li>
            {% endif %}
                </ul>
            </div>
        <div class="col-sm-10 ">{% block content %}{% endblock %}</div>
        </div>
    </div>
    <div>
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{% if message.tags == 'error' %}danger{% elif message.tags == 'info' %}success{% endif %}" role="alert">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
    </div>
</body>
</html>

Autodaktarai/autoservice/templates/car_detail.html
{% extends "base.html" %}

{% block content %}
    {% load static %}
    <h1>{{ carinfo.car }}</h1>

    {% if carinfo.car_image %}
        <img src="{{ carinfo.car_image.url }}" style="margin-bottom: 20px;">
    {% endif %}
    <p><strong>Savininkas: </strong><a href="{% url 'owner' carinfo.car_owner.pk %}">{{ carinfo.car_owner }}</a></p>
    <p><strong>Problema:</strong> {{ carinfo.summary }}</p>
    <p><strong>Automobilio numeriai:</strong> {{ carinfo.plate }}</p>
    <p><strong>Automobilio degalų rūšis:</strong> {{ carinfo.fuel_type }}</p>
    <p><strong>Automobilio variklio darbinis tūris:</strong> {{ carinfo.engine }}</p>
    <p><strong>Automobilio VIN kodas:</strong> {{ carinfo.vin }}</p>
    <p><strong>Automobilį aptarnaujantis darbuotojas:</strong> {{ carinfo.mechanic }}</p> 

    <div style="margin-left:20px;margin-top:20px">
    <h4>Automobilio statusas:</h4>

    {% for status in carinfo.carstatus_set.all %}
        <hr>
        <p><strong>Statusas: </strong> {{ status.get_status_display }} </p>
        <p><strong>Planuojama darbų pabaigos data:</strong> {{ status.due_finish }}</p>
    {% endfor %}
    </div>

    {% if user.is_authenticated %}
    <div class="fieldWrapper">
        <hr><br/>
        <h4>Palikite informaciją apie gedimą:</h4>
        <form action="" method="post">
        {% csrf_token %}
        {{ form.comment }}</br>
        <input type="submit" value="Išsaugoti">
        </form>
    </div>
    {% endif %}

    <div>
        </br>
        <h4>Gedimai:</h4>
            {% if carinfo.carreview_set.all %}
                {% for review in carinfo.carreview_set.all %}
                    <hr>
                    <strong>{{ review.owner }}</strong>, <em>{{ review.date_created}}</em>
                    <p>{{ review.comment }}</p>
                {% endfor %}
            {% else %}
                <p>Automobilis neturi įrašų apie gedimus</p>
        {% endif %}
    </div>
{% endblock %}

Autodaktarai/autoservice/templates/car_list.html
{% extends "base.html" %}

{% block content %}
    {% load static %}
    <h1>Servise esančių automobilių sąrašas</h1>
    {% if car_list %}
    <div class="row">
        {% for car in car_list %}
        <div class="col-md-4 d-flex align-items-stretch">
            <div class="card mb-4 shadow-sm">
                {% if carinfo.car_image %}
                    <img src="{{ carinfo.car_image.url }}" class="card-img-top" alt="...">
                {% else %}
                    <img src="{% static 'img/no-image.png' %}" class="card-img-top">
                {% endif %}
                <div class="card-body">
                    <h6 class="card-subtitle mb-2 text-muted">{{ car.car_owner }}</h6>
                    <p class="card-text"><a href="{% url 'car-detail' car.id %}">{{ car.car }}</a> ({{ car.summary }})</p>
                </div>
            </div>
        </div>
        {% endfor %}
        <div class="pagination">
                <span class="step-links">
                    {% if page_ogj.has_previous %}
                        <a href="?page=1">&laquo; pirmas</a>></a>
                        <a href="?page={{ page_obj.previuos_page_number }}">atgal</a>
                    {% endif %}

                    <span class="current">
                        {{ page_obj.number }} iš {{ page_obj.paginator.num_pages }}
                    </span>

                    {% if page_obj.has_next %}
                        <a href="?page={{ page_obj.next_page_number }}">pirmyn</a>
                        <a href="?page={{ page_obj.paginator_num_pages }}">paskutinis &raquo;</a>
                    {% endif %}
                </span>
        </div>
        {% else %}
        <p>Servise nėra registruotų automobilių</p>
        {% endif %}
{% endblock %}

Autodaktarai/autoservice/templates/index.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% block content %}
    <h1>Autoservisas "Auto daktarai"</h1>
    <p><strong>Automobilių skaičius servise:</strong> {{ car_count }}</p>
    <ul>
        <li><strong>Automobiliai laukiantys eilėje serviso darbams:</strong> {{ waiting_service }}</li>
        <li><strong>Automobiliai inspektuojami servise:</strong> {{ inspection_service }}</li>
        <li><strong>Automobiliai tvarkomi servise:</strong> {{ repair_service }}</li>
        <li><strong>Automobiliai suremontuoti, galima atsiimti:</strong> {{ finish_service }}</li>
    </ul>
    <p>Čia jūs lankotės {{num_visits }}-ą kartą</p>
{% endblock %}

Autodaktarai/autoservice/templates/owner.html
{% extends "base.html" %}

{% block content %}
    <div class="container owner">
    <h4>{{ owner.name }} {{ owner.surname }}</h4>
    <hr/>
    <p>{{ owner.description | safe }}</p>
    </hr>
    </br>
    <h5>Savininkas {{ owner.name }} {{ owner.surname }} servise yra užregistravęs šiuos automobilius:</h5>
    {% for car in owner.cars.all %}
        <li><a href="{% url 'car-detail' car.id %}">{{ owner.car }}</a></li> 
    {% endfor %}
    </div>
{% endblock %}

Autodaktarai/autoservice/templates/owners.html
{% extends "base.html" %}

{% block content %}
    <h1>Automobilių savininkai:</h1>
        {% for owner in owners %}
            <li><a href="{% url 'owner' owner.id %}">{{owner.name}} {{owner.surname}}</a></li>
        {% endfor %}
        <div class="container puslapiai">
            <nav aria-label="...">
                {% if owners.has_other_pages %}
                    <ul class="pagination pagination-sm justify-content-end">
                        {% for i in owners.paginator.page_range %}
                            {% if owners.number == i %}
                                <li class="page-item active">
                                    <a class="page-link">{{ i }}</a>
                                </li>
                            {% else %}
                                <li class="page-item">
                                    <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                                </li>
                            {% endif %}
                        {% endfor %}
                    </ul>
                {% endif %}
            </nav>
        </div>
{% endblock %}

Autodaktarai/autoservice/templates/profilis.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-danger" role="alert">
            {{ message }}
        </div>
        {% endfor %}
        {% endif %}
    <div class="media">
        <img class="rounded-circle account-img" src="{{ user.profilis.nuotrauka.url }}">
        <div class="media-body">
            <h2 class="account-heading">{{ user.username }}</h2>
            <p class="text-secondary">{{ user.email }}</p>
        </div>
    </div>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Profilio info</legend>
                {{ u_form|crispy }}
                {{ p_form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Atnaujinti</button>
            </div>
        </form>
    </div>
{% endblock %}

Autodaktarai/autoservice/templates/register.html
{% extends "base.html" %}

{% block content %}

    <div class="container register">
        <h3>Registracija</h3>
        <form method='post'>
            {% csrf_token %}
            <div class="form-group">
                <label for="username">Vartotojo vardas</label>
                <input name='username' type="text" class="form-control" id="username" aria-describedby="usernameHelp">
                <small id="usernameHelp" class="form-text text-muted">Iki 100 simbolių</small>
            </div>
            <div class="form-group">
                <label for="exampleInputEmail1">El. paštas</label>
                <input name='email' type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                <small id="emailHelp" class="form-text text-muted">El. paštas skirtas tik vartotojo registracijai ir naujam slaptažodžiui išsiųsti</small>
            </div>
            <div class="form-group">
                <label for="password">Slaptažodis</label>
                <input name='password' type="password" class="form-control" id="password" aria-describedby="pwdHelp">
                <small id="pwdHelp" class="form-text text-muted">Ne mažiau, kaip 8 simboliai. Skaičių ir raidžių derinys</small>
            </div>
            <div class="form-group">
                <label for="password2">Pakartoti slaptažodį</label>
                <input name='password2' type="password" class="form-control" id="password2" aria-describedby="pwd2Help">
            </div>
            <button type="submit" class="btn btn-primary register-button">Registruotis</button>
        </form>
        <p>Jeigu užsiregistravote anksčiau, <a href="{% url 'login' %}"><strong>prisijunkite</strong></a></p>
    </div>

{% endblock %}

Autodaktarai/autoservice/templates/search.html
{% extends "base.html" %}

{% block content %}
    <h1>Search "{{query}}" results:</h1>
    </br>
    {% if cars %}
    <ul>
        {% for car in cars %}
            <li>
                <a href="{% url 'car-detail' car.id %}">{{ car.car }}</a> ({{car.plate}})
            </li>
        {% endfor %}
    </ul>
    {% else %}
        <p>Automobilių nerasta</p>
    {% endif %}

{% endblock %}

Autodaktarai/autoservice/templates/user_cars.html
{% extends "base.html" %}

{% block "content" %}
    <h1>Mano registruoti automobiliai autoservise:</h1>

    {% if carstatus_list %}
    <ul>

        {% for carstat in carstatus_list %}
            <img class="rounded-circle" src="{{carstat.owner.profilis.nuotrauka.url}}">
        <li class="{% if carstat.is_overdue %}text-danger{% endif %}">
            <a href="{% url 'car-detail' carstat.car.pk %}">{{carstat.carinfo.car}}</a> ({{ carstat.due_finish }})        
        </li>
        {% endfor %}
    </ul>

    {% else %}
        <p>Šiuo metu servise registruotų automobilių nėra.</p>
    {% endif %}       
{% endblock %}